coverage:
  precision: 2
  round: nearest
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%

ignore:
  - "opt/**/*"
  - "/opt/**/*"
  - "**/opt/**/*"
  - "usr/**/*"
  - "/usr/**/*"
  - "**/usr/**/*"
  - "test/**/*"
  - "**/test/**/*"
  - "build/**/*"
  - "**/build/**/*"
  - "install/**/*"
  - "**/install/**/*"
