name: Run tests and upload coverage
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-22.04
    container:
      image: ros:humble

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y python3-colcon-common-extensions lcov gcovr curl jq gpg
        rosdep update
        rosdep install --from-paths . --ignore-src -r -y
        
    - name: Build with coverage flags
      run: |
        . /opt/ros/humble/setup.sh
        colcon build --packages-select frontier_explorer \
          --cmake-args -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_CXX_FLAGS="--coverage" \
          -DCMAKE_EXE_LINKER_FLAGS="--coverage"

    - name: Run tests
      run: |
        . /opt/ros/humble/setup.sh
        . install/setup.sh
        colcon test --packages-select frontier_explorer --event-handlers console_direct+
        colcon test-result --verbose

    - name: Generate coverage report
      run: |
        . /opt/ros/humble/setup.sh
        . install/setup.sh
        
        # Create initial coverage report
        lcov --directory build/frontier_explorer --capture \
          --output-file coverage.info
          
        # Be more explicit with filtering and use absolute paths
        lcov --remove coverage.info \
          '/opt/*' '/usr/*' '*/test/*' '*/build/*' '*/install/*' \
          --output-file coverage.filtered
        
        # Print filtered report to verify
        echo "=== Filtered Coverage Report ==="
        lcov --list coverage.filtered
  
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.filtered
        fail_ci_if_error: true

    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: coverage_report